### ISSUE TITLE
Section NavBar

### ISSUE THREAD

**Issue by Rafarache** [IDEjr/site-idejr#3]
- REQUISITOS
- [x] Logo a esquerda
Desktop
- [x] Botão( Sobre/Portifólio/Serviços/Contato ) a direita
Mobile
- [x] Burguer Button a direita
- IMAGENS
Desktop
![image](https://user-images.githubusercontent.com/47155967/97344371-6af3e900-1867-11eb-9972-4cce270240ac.png)
Mobile
![image](https://user-images.githubusercontent.com/47155967/97344398-73e4ba80-1867-11eb-9153-bcd2c1d26bfb.png)

**Comment by gabifs** [comment]
- [ ] Adicionar links para as seções na navbar
- [ ] Adicionar `id`s em todos as seções
