### ISSUE TITLE
Section About

### ISSUE THREAD

**Issue by Rafarache** [IDEjr/site-idejr#4]
- Requisitos
- [X] Section Title
- [X] Barra ao lado do texto
- [X] Texto
Desktop
- [x] Social Mídia Icons

- IMAGENS
Desktop
![image](https://user-images.githubusercontent.com/47155967/97345656-181b3100-1869-11eb-8030-6618568c547b.png)
Mobile
![image](https://user-images.githubusercontent.com/47155967/97345698-25382000-1869-11eb-8352-29f9ac741261.png)

- REALIZADO
![image](https://user-images.githubusercontent.com/47155967/100157534-7a2b7e00-2e89-11eb-80d0-4682be70ca28.png)
![image](https://user-images.githubusercontent.com/47155967/100157521-71d34300-2e89-11eb-9c86-84b5c837bad5.png)

**Comment by gabifs** [comment]
- [ ] Faltando o Flecha de background.
- [ ] Verificar as fontes
- [ ] Barra pode ser feita com CSS: pseudo-element before ou first-letter
- [ ] O texto parece estar mto para a esquerda, em telas grandes. Talvez aumentar a fonte em telas grandes.

**Comment by gabifs** [comment]
# Correções na seção

- [ ] Faltando o Flecha de background.
- [ ]  Verificar as fontes
- [ ]  Barra pode ser feita com CSS: pseudo-element before ou first-letter
- [ ]  O texto parece estar mto para a esquerda, em telas grandes. Talvez aumentar a fonte em telas grandes.
