### ISSUE TITLE
Travessão da seção "Quem somos" invade texto

### ISSUE THREAD

**Issue by Henrique-Peixoto** [IDEjr/site-idejr#40]
- [ ]  Travesssão da seção "Quem somos" invade o texto no layout mobile

![Capturar](https://user-images.githubusercontent.com/57225006/113369282-601e1280-9337-11eb-83c4-6493d895a662.PNG)

**Comment by gabifs** [comment]
@Henrique-Peixoto Que estranho, isso não acontece pra mim.

![Screenshot_20210401-221751](https://user-images.githubusercontent.com/21040992/113369687-47fac300-9338-11eb-99b9-bf866ff21d4c.png)

O q tu faz pra ficar assim?

**Comment by Henrique-Peixoto** [comment]
No meu smartphone funciona também, esse print eu tirei do firefox simulando a tela do telefone. Eu uso o Opera Touch como navegador (no celular) e a imagem de fundo dos cards não têm transparência. Não cheguei a testar isso em outros navegadores para celular.

**Comment by gabifs** [comment]
Por algum motivo o firefox não tá reconhecendo o pseudo-element `::first-letter`, que é onde o recuo da linha é aplicado. Firefox, né? sempre bugado :smile:

**Comment by gabifs** [comment]
Pior que eu não consegui descobrir pq não funciona no firefox, ele tem suporte pro isso.
Vou ver se o `text-indent` resolve.

**Comment by gabifs** [comment]
corrigido com `text-indent`
